# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='rain',
            name='date',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
